### ISSUE TITLE
Assertions can be reused

### ISSUE THREAD

**Issue by Class-public** [ory/hydra#3740]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Assertions can be reused.
I think there is something wrong with the deletion logic here，it shouldn't be executed here
```go
func (p *Persister) SetClientAssertionJWT(ctx context.Context, jti string, exp time.Time) (err error) {
	ctx, span := p.r.Tracer(ctx).Tracer().Start(ctx, "persistence.sql.SetClientAssertionJWT")
	defer otelx.End(span, &err)

	// delete expired; this cleanup spares us the need for a background worker
	if err := p.QueryWithNetwork(ctx).Where("expires_at < CURRENT_TIMESTAMP").Delete(&oauth2.BlacklistedJTI{}); err != nil {
		return sqlcon.HandleError(err)
	}

	if err := p.SetClientAssertionJWTRaw(ctx, oauth2.NewBlacklistedJTI(jti, exp)); errors.Is(err, sqlcon.ErrUniqueViolation) {
		// found a jti
		return errorsx.WithStack(fosite.ErrJTIKnown)
	} else if err != nil {
		return err
	}

	// setting worked without a problem
	return nil
}
``` 

### Reproducing the bug

1、Create assertion1 and exchange tokens
2、Create assertion2 and exchange tokens
3、Assertion1 can be used again in exchange for tokens

### Version

v2.1.2

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
As a workaround we can probably use time.Now().UTC() instead of CURRENT_TIMESTAMP to resolve this - contributions welcomed!

**Comment by alnr** [comment]
Cross-linking: **part 2 of this issue looks identical to #4113**, filed July 2026 against PostgreSQL.

Your deadlock dump and their latency analysis are the same statement:

```
DELETE FROM hydra_oauth2_jti_blacklist WHERE nid = ? AND expires_at < CURRENT_TIMESTAMP
```

You saw it as an InnoDB deadlock between two concurrent assertion exchanges; they see it as isolated 100–400 ms spikes on `/oauth2/token` where the time is entirely inside the DB span while the server reports no slow query — the application waiting on a row lock. Different engines, different symptom, one cause: an unbounded `DELETE` over the same expired rows running inline in every request's transaction. #4113 proposes `LIMIT` + `FOR UPDATE SKIP LOCKED`, and a contributor has volunteered.

**Part 1 of your report is separate and still stands**, and it's the more serious half. As you identified, `CURRENT_TIMESTAMP` returns the database server's local time while `expires_at` is stored in UTC, so on a non-UTC database the replay blacklist is pruned against the wrong clock and JTIs can be removed before they expire — widening the window for assertion replay. @aeneasr endorsed `time.Now().UTC()` for this in February 2025.

The convenient part: both fixes rewrite the same line, so they should land together. I've noted that on #4113 so the contributor doesn't scope the change to the contention half and leave the clock bug behind.

Leaving both issues open — this one for part 1, #4113 for the contention.
